package cn.jiliapp.woodenfish.model

import com.google.gson.annotations.SerializedName
/*    {
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIaEdXVWNjSndQWG9wcWZ5UXU3SGZrUnpQYWhIRFpOMG42QTVObUNrTHhjIn0.eyJleHAiOjE2Njg0MjYwMjUsImlhdCI6MTY2ODM5MDAyNiwianRpIjoiMTg5MzQ1MGQtNDk5Ni00YWZlLWJjZjUtODZiN2FkODgzZjkxIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5qaWxpYXBwLmNuL3JlYWxtcy9wbGF0Zm9ybSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjNzcxMmE1Yy0zNmZjLTRlMDctOWI1My01MzQzNDZhNTJkY2QiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJqaWxpYXBwX3N3YWdnZXJfY2xpZW50SWQiLCJzZXNzaW9uX3N0YXRlIjoiMjZjYTkwMDUtYWI2OS00YTljLWFkNTYtN2Y5YjhlMzJmMjBkIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vYXBpLmppbGlhcHAuY24iXSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHVzZXJJZCIsInNpZCI6IjI2Y2E5MDA1LWFiNjktNGE5Yy1hZDU2LTdmOWI4ZTMyZjIwZCIsInJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXBsYXRmb3JtIl0sInVzZXJJZCI6IjE1NDE2OTMzMzM0MzU0NTM0NDEifQ.KlZcVfU9oOWeODBLsWdpAH9PJXNMOchUO-dAo-V8yUEZjjcasdBnXbPPtHBdi1xRz3pPEyBC18t7UlkHf9cqLkjp5_fv9hvUkChGl1Rdyz5fk9EgMu65jTcAURatn-v4gVFEwZe-RL-RqpRpjyAJr77TgOFVHZZvvNbVuQjp4RqDz0jE_LvZTzrM6mNFWtKlPbCvTFhy7xyMqjqCeCD19WyJsA8zAt6phbM4h-sDTr6lITNyflOoA5WdOs820qyJTejkEePJFq_wGRFZMf-dfdnRs2IaPsqLdg2UB_-e4rWhksIiti5tuovAwBLGQyuo5AC2UVe6uozwS3iqIBzyQQ",
    "expires_in": 35999,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YTZhOTMxZC02ZGE5LTRkMDQtYWZmOS0xMjZkMzNlODZjMDEifQ.eyJleHAiOjE2NjgzOTE4MjYsImlhdCI6MTY2ODM5MDAyNiwianRpIjoiNjZlODU0YjktMWU5ZC00ZTM3LWJmNDctMjllYjlhOGU5NDk5IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5qaWxpYXBwLmNuL3JlYWxtcy9wbGF0Zm9ybSIsImF1ZCI6Imh0dHBzOi8va2V5Y2xvYWsuamlsaWFwcC5jbi9yZWFsbXMvcGxhdGZvcm0iLCJzdWIiOiJjNzcxMmE1Yy0zNmZjLTRlMDctOWI1My01MzQzNDZhNTJkY2QiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiamlsaWFwcF9zd2FnZ2VyX2NsaWVudElkIiwic2Vzc2lvbl9zdGF0ZSI6IjI2Y2E5MDA1LWFiNjktNGE5Yy1hZDU2LTdmOWI4ZTMyZjIwZCIsInNjb3BlIjoib3BlbmlkIHVzZXJJZCIsInNpZCI6IjI2Y2E5MDA1LWFiNjktNGE5Yy1hZDU2LTdmOWI4ZTMyZjIwZCJ9.4iWoT9jyuuLiMU4gtqeia_eF42s12ou-TX1yJ9FaSHA",
    "token_type": "Bearer",
    "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIaEdXVWNjSndQWG9wcWZ5UXU3SGZrUnpQYWhIRFpOMG42QTVObUNrTHhjIn0.eyJleHAiOjE2Njg0MjYwMjUsImlhdCI6MTY2ODM5MDAyNiwiYXV0aF90aW1lIjowLCJqdGkiOiIwYzAxMjBlZi1jNDdkLTQzODktOGYxMi1lMzBiMjBhN2FkZjIiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmppbGlhcHAuY24vcmVhbG1zL3BsYXRmb3JtIiwiYXVkIjoiamlsaWFwcF9zd2FnZ2VyX2NsaWVudElkIiwic3ViIjoiYzc3MTJhNWMtMzZmYy00ZTA3LTliNTMtNTM0MzQ2YTUyZGNkIiwidHlwIjoiSUQiLCJhenAiOiJqaWxpYXBwX3N3YWdnZXJfY2xpZW50SWQiLCJzZXNzaW9uX3N0YXRlIjoiMjZjYTkwMDUtYWI2OS00YTljLWFkNTYtN2Y5YjhlMzJmMjBkIiwiYXRfaGFzaCI6IkRqdG5aOC1CZ1laT2tqSzQ1dW5uNGciLCJhY3IiOiIxIiwic2lkIjoiMjZjYTkwMDUtYWI2OS00YTljLWFkNTYtN2Y5YjhlMzJmMjBkIiwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtcGxhdGZvcm0iXSwidXNlcklkIjoiMTU0MTY5MzMzMzQzNTQ1MzQ0MSJ9.aDMmSU6byODqvI7wkB-VlXuCLX01HjYGNqOduvbxH0k0_nyoitt3lh5P4TPv51ifIRbt2MGVRGO7BC672QKBugMons2l4KcpO570IVEU6pZoFbHbtkFwRbrLhJjecYq6i-PMlzQFDQRuAXAbO2AVbn98skXMepd1PYLfWOL-TACmII1bDULkdP_wAVZpbsp7I5q9vbX5FiBY3zJ3dcHR1hzANS0aiGX3kgI1-ySJXuqbvSYESZmkvjOrKzwX3Vg0MlV28AYlqma-Z7dqk-KYZaurPh5rk18pwWQWKcCikg8bLj36RHxV-Tv26kqfZ2_sUBuRxetWVEr7GYlNUu1Avg",
    "not-before-policy": 0,
    "session_state": "26ca9005-ab69-4a9c-ad56-7f9b8e32f20d",
    "scope": "openid userId"
}*/
class KcAuthVO (
    @SerializedName("access_token")
    val accessToken: String,
    @SerializedName("expires_in")
    val expiresIn: Int,
    @SerializedName("refresh_expires_in")
    val refreshExpiresIn: Int,
    @SerializedName("refresh_token")
    val refreshToken: String,
    @SerializedName("token_type")
    val tokenType: String,
    @SerializedName("id_token")
    val idToken: String,
    @SerializedName("not-before-policy")
    val notBeforePolicy: Int,
    @SerializedName("session_state")
    val sessionState: String,
    @SerializedName("scope")
    val scope: String,
    )

